<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Description>Adds latitude/longitude to electorate location lookup to AustralianElectorates using NetTopologySuite (https://nettopologysuite.github.io/).</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NetTopologySuite" />
    <PackageReference Include="NetTopologySuite.IO.GeoJSON4STJ" />
    <ProjectReference Include="..\AustralianElectorates\AustralianElectorates.csproj" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Sbom.Targets" PrivateAssets="all" Condition="'$(CI)' == 'true'" />
  </ItemGroup>
</Project>
