image: Visual Studio 2022
build_script:
- cmd: dotnet build src --configuration Release
test:
  categories:
    except:
    - Integration
artifacts:
- path: nugets\*.nupkg
on_failure:
  - ps: Get-ChildItem *.received.* -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }