<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Argon" Version="0.37.0" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="Bogus" Version="35.6.5" />
    <PackageVersion Include="CountryData" Version="6.20.0" />
    <PackageVersion Include="GeoJSON.Net" Version="1.4.1" />
    <PackageVersion Include="HtmlAgilityPack" Version="1.13.0" />
    <PackageVersion Include="MarkdownSnippets.MsBuild" Version="28.4.4" />
    <PackageVersion Include="NetTopologySuite" Version="2.6.0" />
    <PackageVersion Include="NetTopologySuite.IO.GeoJSON" Version="4.0.0" />
    <PackageVersion Include="NetTopologySuite.IO.Esri.Shapefile" Version="1.2.0" />
    <PackageVersion Include="ProjectDefaults" Version="1.0.181" />
    <PackageVersion Include="ProjectFiles" Version="1.4.0" />
    <PackageVersion Include="Sbom" Version="0.2.0" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="4.1.2" />
    <PackageVersion Include="Verify.XunitV3" Version="33.1.4" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="DiffEngine" Version="20.5.1" />
    <PackageVersion Include="EmptyFiles" Version="8.19.0" />
    <PackageVersion Include="SimpleInfoName" Version="3.2.0" />
    <PackageVersion Include="Verify" Version="33.1.4" />
  </ItemGroup>
</Project>
